[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'

[tool.pylint.messages_control]
disable = [
    "C0111",  # missing-docstring
    "C0103",  # invalid-name
    "E0401",  # import-error
]

[tool.mypy]
python_version = "3.7"
warn_return_any = true
warn_unused_configs = true

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
